### ISSUE TITLE
favとRTの数を表示してほしい

### ISSUE THREAD

**Issue by fcijpbgiec-ib** [Yukineko-mew/YukitterTweetOnly#25]
タイトルそのまま。位置はツイートの下のほうに？

**Comment by y-oga-819** [comment]
やった。

**Comment by y-oga-819** [comment]
[![LGTM](http://www.lgtm.in/p/s2Kjz42On)](http://www.lgtm.in/i/s2Kjz42On)

[:+1:](http://www.lgtm.in/u/s2Kjz42On) [:-1:](http://www.lgtm.in/r/s2Kjz42On)
